INSERT INTO "TIPO_DOCUMENTO" VALUES ('DNI', 'Documento Nacional de Identidad');
INSERT INTO "TIPO_DOCUMENTO" VALUES ('PAS', 'Pasaporte');
INSERT INTO "TIPO_DOCUMENTO" VALUES ('CE', 'Carnet de Extranjería');

INSERT INTO "EMPRESA" VALUES ('INTEGRA', 'AFP Integra');
INSERT INTO "EMPRESA" VALUES ('FONDOS', 'Fondos SURA');
INSERT INTO "EMPRESA" VALUES ('SAB', 'SAB SURA');